### ISSUE TITLE
[MS-IME]取り込みエラーについて

### ISSUE THREAD

**Issue by u83ism** [heppokofrontend/hololive-dictionary#1]
こんにちは。公開してくれてありがとうございます。助かりました。
ただ[ms-ime-dict--all.txt](https://github.com/heppokofrontend/hololive-dictionary/blob/main/dictionary/win/ms-ime-dict--all.txt)をWindows10環境で取り込もうとすると、何件かエラーが発生したので確認しました。

# エラーログ

```
! 指定された単語は既に登録されています。
んなひめ	んな姫	名詞

! 指定された単語は既に登録されています。
myth	HoloMyth	名詞

! 指定された単語は既に登録されています。
myth	#HoloMyth	名詞

! 指定された単語は既に登録されています。
myth	Myth	名詞

! 指定された単語は既に登録されています。
myth	Hololive English -Myth-	名詞

! 指定された単語は既に登録されています。
Myth	HoloMyth	名詞

! 指定された単語は既に登録されています。
Myth	#HoloMyth	名詞

! 指定された単語は既に登録されています。
Myth	Myth	名詞

! 指定された単語は既に登録されています。
Myth	Hololive English -Myth-	名詞
```

# 原因
テキストファイルを調べたところ、

- 「んなひめ」が[1485行目](https://github.com/heppokofrontend/hololive-dictionary/blob/main/dictionary/win/ms-ime-dict--all.txt#LL1485)、[1529行目](https://github.com/heppokofrontend/hololive-dictionary/blob/main/dictionary/win/ms-ime-dict--all.txt#LL1529)と重複している
- 「Myth」を全角と半角で登録しようとしているがMS-IMEは区別せずに扱うため重複扱いになってるっぽい

のが問題のようです。

**Comment by heppokofrontend** [comment]
@u83ism ゆうやみさん🙋‍♂️
ご連絡ありがとうございます！

WindowsのIMEは全半角考慮しないんですね👀
こちら修正しましたので近々 main ブランチにマージします！

- #3

2年前から更新できてないので、新しく増えたメンバーについても追加したいですね…

**Comment by heppokofrontend** [comment]
マージ済みなのでクローズします。
