### ISSUE TITLE
[ 追加リクエスト ] Advent、ReGLOSSのメンバー

### ISSUE THREAD

**Issue by YuriArata** [heppokofrontend/hololive-dictionary#18]
Advent、ReGLOSSのメンバーの情報を追加していただきたいです！

## 単語についての情報源を以下に貼ってください

ホロライブEnglish -Advent-
- https://hololive.hololivepro.com/talents?gp=advent

hololive DEV_IS ReGLOSS
- https://prtimes.jp/main/html/rd/p/000000978.000030268.html
- https://hololive.hololivepro.com/special/9491/

**Comment by heppokofrontend** [comment]
@YuriArata Issueありがとうございます！  
PRいただいていたので、次回リリースに含めました！

- #19 
- #20 

https://github.com/heppokofrontend/hololive-dictionary/releases/tag/v1.8.0
